export const IITK_DEPARTMENT_OPTIONS = [
  { value: 'Aerospace Engineering', label: 'Aerospace Engineering' },
  { value: 'Biological Sciences & Bioengineering', label: 'Biological Sciences & Bioengineering' },
  { value: 'Chemical Engineering', label: 'Chemical Engineering' },
  { value: 'Civil Engineering', label: 'Civil Engineering' },
  { value: 'Computer Science & Engineering', label: 'Computer Science & Engineering' },
  { value: 'Electrical Engineering', label: 'Electrical Engineering' },
  { value: 'Materials Science & Engineering (includes Materials Science Programme)', label: 'Materials Science & Engineering (includes Materials Science Programme)' },
  { value: 'Mechanical Engineering', label: 'Mechanical Engineering' },
  { value: 'Management Sciences (includes Department of Management Sciences & Management)', label: 'Management Sciences (includes Department of Management Sciences & Management)' },
  { value: 'Design', label: 'Design' },
  { value: 'Sustainable Energy Engineering', label: 'Sustainable Energy Engineering' },
  { value: 'Space, Planetary and Astronomical Sciences and Engineering', label: 'Space, Planetary and Astronomical Sciences and Engineering' },
  { value: 'Intelligent Systems (includes Wadhwani School of AI & Intelligent Systems)', label: 'Intelligent Systems (includes Wadhwani School of AI & Intelligent Systems)' },
  { value: 'Chemistry', label: 'Chemistry' },
  { value: 'Earth Sciences', label: 'Earth Sciences' },
  { value: 'Physics', label: 'Physics' },
  { value: 'Mathematics & Statistics', label: 'Mathematics & Statistics' },
  { value: 'Cognitive Science', label: 'Cognitive Science' },
  { value: 'Humanities and Social Sciences (includes Humanities)', label: 'Humanities and Social Sciences (includes Humanities)' },
  { value: 'Economics (includes Economic Sciences)', label: 'Economics (includes Economic Sciences)' },
  { value: 'Gangwal School of Medical Science & Technology', label: 'Gangwal School of Medical Science & Technology' },
  { value: 'Kotak School of Sustainability', label: 'Kotak School of Sustainability' },
  { value: 'Nuclear Engineering & Technology', label: 'Nuclear Engineering & Technology' },
  { value: 'Photonics Science and Engineering Programme', label: 'Photonics Science and Engineering Programme' },
];
